### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Band-hi#1]
[Sintesis Gestion de Calidad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Band-hi/files/9603075/Sintesis.Gestion.de.Calidad.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
